;;THIS SCRIPT IS FOR LINUX + DVORAK.  AUTOHOTKEY-v1.0.  TESTED ON DEBIAN-MATE-12.6.  CONVERT THE SYSTEM KEYBOARD FIRST!  WINDOW SPY REQUIRES PROPER ahk_x11.AppImage INSTALLATION.
;;HOTKEYS:  LockWorkStation RWIN  TRANSPARENCY #t  EXPLORER !e  RENAME !r  DUPLICATE ^d  ALWAYSONTOP ^SPACE  SUSPEND (^!SPACE DOUBLE-TAP)  WINDOW-LIST F11  HIDDEN-WINDOWS +F11.  
;;NO <! FOR LALT,  NOR MOUSE ALTS.  LINUX CAPSLOCK REGISTERS DIFFERENTLY, SO USE * WHEREVER POSSIBLE.  EXAMPLES: CAPPED F12 & SPACE ARE DIFFERENT TO F12 & SPACE, ETC.  MAPPING QWERTY→DVORAK TOO RISKY. BUT IN PRINCIPLE AHK SHOULD MAP THE WHOLE KEYBOARD.  THIS SCRIPT GENERALLY CLONES CTRL WITH ALT (!c/!v FOR COPY/PASTE, ETC).  PRESS CTRL/ALT AGAIN IF IT FAILS TO RELEASE DUE TO LAGGY SEND.
;;~100 LINES & ~800 WORDS.

#SINGLEINSTANCE
MENU TRAY,TIP,AHKVersion %A_AHKVERSION%
MENU TRAY,ADD  ;DIVIDER.
MENU TRAY,ADD
MENU TRAY,ADD,ALWAYSONTOP TOGGLE `t #SPACE, #*SPACE ;A MONOSPACE FONT WOULD BE PREFERRED, LIKE COURIER NEW.  TRAY,DEFAULT INVALID.
MENU TRAY,ADD,TRANSPARENCY       `t #t    , #*t  
MENU TRAY,ADD,TRANSPARENCY OFF   `t #+t   ,#+*t    ;+ IS SHIFT.
MENU TRAY,ADD 
MENU TRAY,ADD,WINGETLIST         `t  F11  ,  *F11    ;SIMPLE LIST OF WINDOWS.
MENU TRAY,ADD,WINGETLIST`, FULL  `t +F11  , +*F11    ;FULL LIST.
MENU TRAY,ADD                               
MENU TRAY,ADD,DUPLICATE          `t !d    , !*d     ;NON-TRIVIAL EXAMPLE.  !e & !r ARE TRIVIAL.
MENU TRAY,ADD,LockWorkStation    `t  RWIN ,  *RWIN

     !*'::          ;TOP ROW.  THERE'S A BUG IF ALT/CTRL ARE RELEASED BEFORE THE SEND IS COMPLETED (LAG BUG). MUST PUSH ALT AGAIN TO RELEASE IT.  AN ALTERNATIVE IS TO ALSO SEND {ALT} TO FORCE RELEASE, WHICH BLOCKS DOUBLE-PASTE AS A SIDE-EFFECT.
     ^*'::SEND ^q   ;q QUIT, COMMENT TOGGLE. ^ IS CTRL.  SEND REQUIRED FOR THE ALTS, BUT NOT ON V2. 
     !*.::          
     ^*.::
     #*.::SEND #e   ;e EXPLORER.
     !*p::          
     ^*p::SEND {F2} ;r RENAME.
    !+*y::              
    ^+*y::
    #+*y::
    #+*t::WINSET TRANSPARENT,OFF,A ;t TRANSPARENCY.  A ACTIVE WINDOW.  +* GO FIRST.  OFF=255 (BUT MORE EFFICIENT).
     !*y::            
     ^*y::
     #*y::
     #*t::WINSET TRANSPARENT,128,A 
     !*g::      
     ^*g::SEND ^u     ;u URL OPEN (SMPLAYER).
     !*r::            
     ^*r::SEND ^o     ;o OPEN.
     
     !*a::SEND ^a     ;a ALL.  HOME ROW. 
     !*o::            
     ^*o::
     !*s::SEND ^s     ;s SAVE.  DVORAK USERS ALSO COPY/PASTE WITH 2 HANDS. APPLIES TO s d f z c x v.
     !*u::            
     ^*u::
     !*f::SEND ^f     ;f FIND.
     
     !*;::
     ^*;::
     !*z::SEND ^z     ;z UNDO/REDO.
     !*q::            
     ^*q::
     !*x::SEND ^x     ;x CUT.
     !*j::            
     ^*j::
     !*c::SEND ^c     ;c COPY.
     !*k::
     ^*k::
     !*v::SEND ^v     ;v PASTE.

^!*SPACE::SUSPEND       ;DOUBLE-TAP REQUIRED.  IMMUNE TO SUSPENSION.  THIS GOES BEFORE ^SPACE.
 !*SPACE::              ;BUG: !SPACE ACTIVATES IN LINUX.
 ^*SPACE::
 #*SPACE::WINSET ALWAYSONTOP,TOGGLE,A  ;ALSO VALID ON WIN98.
     #*n::
   *RWIN::SEND #l       ;RWIN LOCKWORKSTATION.  RWIN-LOCK CAN BE ANNOYING IF A PASSWORD IS LONG OR UNKNOWN. BUT IT COULD ALSO PREVENT SEIZURE OF A SYSTEM WHICH IS TOO DIFFICULT TO LOCK.

 !+*LEFT::SEND ^+{LEFT} ;JUMPS SELECTION LEFT OR RIGHT.  UNFORTUNATELY ALTS ARE SLOW!
  !*LEFT::SEND  ^{LEFT} ;JUMPS BY A WORD LEFT OR RIGHT.  THIS STOPS FLIPPING WORDS AROUND.  MOUSE ALTS AREN'T WORTH THE EFFORT ON v1.0.
!+*RIGHT::SEND ^+{RIGHT}
 !*RIGHT::SEND  ^{RIGHT}

^*e::            
!*e::
^*d::
!*d::  ;d DUPLICATE.  ALT PREFERRED.
    WINGET      PROCESSNAME,PROCESSNAME,A
    STRINGSPLIT PROCESSNAME,PROCESSNAME,`n ;LINUX PROCESSNAME USUALLY TERMINATES WITH `n INSTEAD OF .exe.
    SEND          ^c                       ;2 SENDS MORE RELIABLE. 
    SENDVAR     = ^v^v
    IFEQUAL PROCESSNAME1,explorer.exe ;LINUX CASE SENSITIVE.  EXPLORER PASTES ONCE ONLY. 
        SENDVAR = ^v
    IFEQUAL PROCESSNAME1,finder       ;MACOS?
        SENDVAR = ^v
    IFEQUAL PROCESSNAME1,caja         ;MATE.
        SENDVAR = ^v
    IFEQUAL PROCESSNAME1,nautilus     ;GNOME.
        SENDVAR = ^v
    IFEQUAL PROCESSNAME1,dolphin      ;KDE.
        SENDVAR = ^v
    SEND          %SENDVAR%
    RETURN

!*F11::SEND {F11} ;!F11 CAN DO WHATEVER F11 SHOULD DO.
+*F11::           ;HIDDEN WINDOW LIST.  LINUX SLOW.  V2 HAS CONTROLLIST (^F11).  F12 FOR TITLEBAR TOGGLE.
    DETECTHIDDENWINDOWS ON
    WINGET LIST ,LIST ,,,""
    WINGET COUNT,COUNT,,,""
    MSG = %COUNT% WINDOWS TOTAL. CLASSES BELOW.`n
    LOOP  %COUNT% 
    {
        ahk_id := LIST%A_INDEX%
        WINGETCLASS CLASS,ahk_id %ahk_id%
        MSG = %MSG%%A_INDEX% %CLASS%‎  ‎ ;'‎' IS INVISIBLE LRM.  ALTERNATIVE CAN SET  SPACE := "  " & EVALUATE %S%.  
    }
    MSGBOX %MSG%
    RETURN

*F11::  ;WINDOW LIST.  LINUX SLOW.  
    DETECTHIDDENWINDOWS ON  
    WINGET FULLCOUNT,COUNT,,,""  ;HIDDEN COUNT.  ~270 IN DEBIAN-MATE.  MINIMIZED COUNTS AS HIDDEN, ON LINUX.
    DETECTHIDDENWINDOWS OFF
    WINGET LIST     ,LIST ,,,""
    WINGET COUNT    ,COUNT,,,""
    WINGETTITLE ACTIVETITLE,A
    MSG = %COUNT% WINDOWS, +%FULLCOUNT%-%COUNT% HIDDEN`n`n`n
    LOOP  %COUNT% 
    {
        HWND  := LIST%A_INDEX%  ;:= EVALUATES.
        ahk_id = ahk_id %HWND%  ;LOWERCASE FOR LINUX.
        WINGET      PID        ,PID        ,%ahk_id% 
        WINGET      PROCESSNAME,PROCESSNAME,%ahk_id%  ;PROCESSPATH INVALID. MINMAX=-1.
        STRINGSPLIT PROCESSNAME,PROCESSNAME,`n        ;SEPARATE `n (OPTIONAL).
        WINGETPOS   X,Y,W,H                ,%ahk_id%
        WINGETCLASS CLASS                  ,%ahk_id%
        WINGETTITLE WINTITLE               ,%ahk_id%
        ACTIVE     = 
        IFEQUAL WINTITLE,%ACTIVETITLE%
            ACTIVE = ACTIVE`t
        MSG        = %MSG%%A_INDEX%: %ACTIVE% %WINTITLE%`n %PROCESSNAME1%`t CLASS=%CLASS%`t PID=%PID%`t X,Y,W,H=%X%,%Y%,%W%,%H%`t HWND=%HWND%`n`n  ;CAPS ARE LIKE FLAGS.
    }
    MSGBOX %MSG%
    RETURN


;;FUTURE VERSION NEEDS LIST OF EXPLORERS, ON TOP. AFFECTS TRUE DUPLICATOR.

